apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://example.com/your-org/homelab-gitops
    path: infrastructure
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  syncPolicy:
    automated: {}
