apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: argocd
      labels:
        app.kubernetes.io/name: argocd
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: platform
      labels:
        purpose: platform
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: monitoring
      labels:
        purpose: observability
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: apps
      labels:
        purpose: applications
