apiVersion: v1
kind: Secret
metadata:
  name: example-secret
  namespace: platform
type: Opaque
data:
  username: YWRtaW4= # base64 for 'admin'
  password: cGFzc3dvcmQ= # base64 for 'password'

# To create a SealedSecret, install the Sealed Secrets controller and run:
# kubeseal --controller-name=sealed-secrets --format=yaml < example-secret.yaml > example-sealedsecret.yaml
