apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    # allow role:ci to get and sync Applications (narrow this to specific apps in production)
    p, role:ci, applications, get, */*, allow
    p, role:ci, applications, sync, */*, allow
    # map user 'ci-bot' to role:ci
    g, ci-bot, role:ci
