apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-standard
provisioner: nfs.csi.k8s.io
parameters:
  server: "10.0.0.10" # replace with your NFS server IP or DNS
  share: "/export/k8s"
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true

# Replace `server` and `share` parameters with values from your NFS server.
